// <auto-generated />
using System;
using Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo.Migrations
{
    [DbContext(typeof(EXDbContext))]
    [Migration("20230507120641_Test")]
    partial class Test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Infrastructure.Entities.User", b =>
                {
                    b.Property<int>("uID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActived")
                        .HasColumnType("bit");

                    b.Property<string>("uEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("uSex")
                        .HasColumnType("bit");

                    b.HasKey("uID");

                    b.ToTable("wsUser");
                });

            modelBuilder.Entity("Infrastructure.Entitites.HocSinh", b =>
                {
                    b.Property<int>("uID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("uDiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("uGioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("uHoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("uNgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("uSoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("uID");

                    b.ToTable("wsHocSinh");
                });
#pragma warning restore 612, 618
        }
    }
}
